### ISSUE TITLE
不要なファイル

### ISSUE THREAD

**Issue by yu-tang** [5t111111/ja.crystal-lang.org-omegat#1]
OmegaT のチームプロジェクトとしては不要なファイルがあるので、リポジトリから削除すると良いかもリストを作ってみました。
## たぶん現在のリポジトリ名に変更する前に作成されたと思われる古い翻訳メモリ ファイル
- ./crystal-jp-gh-pages-level1.tmx
- ./crystal-jp-gh-pages-level2.tmx
- ./crystal-jp-gh-pages-omegat.tmx
## クライアント側で OmegaT によって必ず上書きされるので、サーバー側に置く意味がないファイル
- ./omegat/last_entry.properties
- ./omegat/project_stats.txt

いずれも、有って害にはなりませんが、利用者によっては軽く混乱する可能性があるので、削除して新年を迎えるとスッキリするかも（個人の意見です

**Comment by yu-tang** [comment]
## 状況によっては不要かもしれないファイル
- ./omegat/files_order.txt

これは翻訳対象ファイル一覧の表示順序を制御する設定ファイルですが、特に制御する意図が無い場合は不要なのと、あと設定値が現行のディレクトリ構成と食い違っている（'crystal-jp-gh-pages` という今は実在しないディレクトリが指定されている）ので、たぶんどのみち機能してないです。
- ./crystal-jp-gh-pages-omegat-level1.tmx
- ./crystal-jp-gh-pages-omegat-level2.tmx
- ./crystal-jp-gh-pages-omegat-omegat.tmx

これは外部連携用のファイルなので、OmegaT 単体で考えると要らない（Git 管理外で問題ない）です。
ただこれらのファイルがあること自体は必ずしも問題なわけではなくて、たとえば OmegaT は持ってないし使わないけれども、別の CAT ツール（Trados とか MemoQ とか）で翻訳メモリを流用したいというユーザーがいた場合は、リポジトリに置いておくことによって、そのユーザーが必要なファイルだけダウンロードできるというメリットはあります。
逆に言うと、翻訳メモリを利用するユーザーが必ず OmegaT を使うという前提なら、まったく要らないです。

**Comment by 5t111111** [comment]
ありがとうございます！何度かプロジェクト名(ディレクトリ名)を変えて整理していなかったので助かりました！

不要と思われるファイルは削除して、`./omegat/last_entry.properties` などは `.gitignore` に追加しました。`./omegat/files_order.txt` などは意識したことすらなかったので勉強になります！

外部連携用ファイルは一応残しました。
