### ISSUE TITLE
ファイルフィルター設定の文字エンコーディング

### ISSUE THREAD

**Issue by yu-tang** [5t111111/ja.crystal-lang.org-omegat#2]
現状の設定だと、テキストファイルフィルターの文字エンコーディングが「自動」になっています。

![filter-setting](https://cloud.githubusercontent.com/assets/578576/12005601/95f102c4-abf1-11e5-8b00-eafb2538cb60.png)

この「自動」っていうのがちょっと危うくて、少なくとも Windows 環境下だと、添付画像でお分かりのように、ファイルによってエンコーディングがバラついてしまいます。たぶんファイルに含まれる文字種によって OS の既定エンコーディングにフォールバックされるものがあるからだと思います（自信ナシ）。Mac だと UTF-8 で統一される（たぶん）ので気づきにくいですが、OS の既定エンコーディングが UTF-8 ではない環境下で開くとこうなってしまいます。

![source-file-list](https://cloud.githubusercontent.com/assets/578576/12005603/a016cab8-abf1-11e5-82ea-41c7fbb82eb1.png)

Mac ユーザーしかいないのであれば問題ないですが、他のプラットフォームのユーザーも使う可能性がある場合は、テキストファイルフィルターの文字エンコーディングを明示的に UTF-8 に設定しておくのが無難だと思います。

ちなみに、設定は `./omegat/filters.xml` に保存されています。

**Comment by 5t111111** [comment]
ありがとうございます！これは良くないですね。UTF-8に設定しました！
