### ISSUE TITLE
チーム機能をオフにする方法

### ISSUE THREAD

**Issue by yu-tang** [5t111111/ja.crystal-lang.org-omegat#3]
OmegaT のヘルプに載っていますが、コマンドラインスイッチ `no-team` を指定して起動すると、Git 連携（SVN でも一緒ですが）を無効にして起動できます。

```
java -jar OmegaT.jar /path/to/project --no-team
```

Windows だと、そういうショートカットを作るなりランチャに登録するなりで、OK です。

Mac でも同様だろうと思います（すみません、Mac ユーザーじゃないので具体的に言えないです…）。

自前でビルドするよりは楽になるかな、と思います。

**Comment by 5t111111** [comment]
うおおお知らなかった…確かにヘルプのコマンドラインオプションに記載がありますね…見落としていました。

[Qiitaの記事](http://qiita.com/5t111111/items/d1e40b907e5e58e4c71d#omegat)も修正しました！ありがとうございます！
